### ISSUE TITLE
flaky test

### ISSUE THREAD

**Issue by vigith** [numaproj/numaflow#11]
```
2022-05-24T18:29:10.0207030Z === RUN   TestJetStreamBufferWriterBufferFull
2022-05-24T18:29:10.0208160Z     writer_test.go:167: 
2022-05-24T18:29:10.0208496Z            Error Trace:    writer_test.go:167
2022-05-24T18:29:10.0209167Z            Error:          Expected nil, but got: isb.BufferWriteErr{Name:"testJetStreamBufferWrite", Full:true, InternalErr:false, Message:"Buffer full!"}
2022-05-24T18:29:10.0209684Z            Test:           TestJetStreamBufferWriterBufferFull
2022-05-24T18:29:10.0209994Z     writer_test.go:167: 
2022-05-24T18:29:10.0210640Z            Error Trace:    writer_test.go:167
2022-05-24T18:29:10.0211344Z            Error:          Expected nil, but got: isb.BufferWriteErr{Name:"testJetStreamBufferWrite", Full:true, InternalErr:false, Message:"Buffer full!"}
2022-05-24T18:29:10.0211863Z            Test:           TestJetStreamBufferWriterBufferFull
2022-05-24T18:29:10.0227631Z     writer_test.go:174: 
2022-05-24T18:29:10.0228178Z            Error Trace:    writer_test.go:174
2022-05-24T18:29:10.0228590Z            Error:          An error is expected but got nil.
2022-05-24T18:29:10.0229042Z            Test:           TestJetStreamBufferWriterBufferFull
2022-05-24T18:29:10.0229716Z --- FAIL: TestJetStreamBufferWriterBufferFull (2.03s)
2022-05-24T18:29:10.0230319Z panic: runtime error: invalid memory address or nil pointer dereference [recovered]
2022-05-24T18:29:10.0230801Z    panic: runtime error: invalid memory address or nil pointer dereference
2022-05-24T18:29:10.0231363Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1312bd6]
2022-05-24T18:29:10.0231765Z 
2022-05-24T18:29:10.0231887Z goroutine 198 [running]:
2022-05-24T18:29:10.0232206Z testing.tRunner.func1.2({0x13ca380, 0x1dfc2f0})
2022-05-24T18:29:10.0232915Z    /opt/hostedtoolcache/go/1.17.10/x64/src/testing/testing.go:1209 +0x36c
2022-05-24T18:29:10.0233242Z testing.tRunner.func1()
2022-05-24T18:29:10.0233796Z    /opt/hostedtoolcache/go/1.17.10/x64/src/testing/testing.go:1212 +0x3b6
2022-05-24T18:29:10.0234354Z panic({0x13ca380, 0x1dfc2f0})
2022-05-24T18:29:10.0235031Z    /opt/hostedtoolcache/go/1.17.10/x64/src/runtime/panic.go:1047 +0x266
2022-05-24T18:29:10.0235506Z github.com/numaproj/numaflow/pkg/isb/jetstream.TestJetStreamBufferWriterBufferFull(0x0)
2022-05-24T18:29:10.0236269Z    /home/runner/work/numaflow/numaflow/pkg/isb/jetstream/writer_test.go:175 +0x776
2022-05-24T18:29:10.0236627Z testing.tRunner(0xc0000fed00, 0x15417b8)
2022-05-24T18:29:10.0236996Z    /opt/hostedtoolcache/go/1.17.10/x64/src/testing/testing.go:1259 +0x230
2022-05-24T18:29:10.0237304Z created by testing.(*T).Run
2022-05-24T18:29:10.0237661Z    /opt/hostedtoolcache/go/1.17.10/x64/src/testing/testing.go:1306 +0x727
2022-05-24T18:29:10.0238011Z FAIL       github.com/numaproj/numaflow/pkg/isb/jetstream  3.261s
```

**Comment by vigith** [comment]
closed by #9
