### ISSUE TITLE
Kafka source is not reading message from kafka 

### ISSUE THREAD

**Issue by sarabala1979** [numaproj/numaflow#1521]
**Describe the bug**
The pipeline has only one Kafka input source pod. it suddenly stops reading the message from kafka.

Related Issue #1442

**Log**
```log4j
{"level":"info","ts":"2024-02-24T01:41:58.774345703Z","logger":"numaflow.Source-processor","caller":"sarama@v1.40.1/sarama.go:129","msg":"client/metadata fetching metadata for [service-trace-metrics-osam] from broker eventbus-kafka.pl-data-lake-prd.a.intuit.com:19801","pipeline":"osam-otlp-service-trace","vertex":"in"}
{"level":"info","ts":"2024-02-24T01:41:58.77737952Z","logger":"numaflow.Source-processor","caller":"sarama@v1.40.1/sarama.go:129","msg":"client/coordinator requesting coordinator for service-trace-metrics-prd-osam-01 from eventbus-kafka.pl-data-lake-prd.a.intuit.com:19801","pipeline":"osam-otlp-service-trace","vertex":"in"}
{"level":"info","ts":"2024-02-24T01:41:58.778487432Z","logger":"numaflow.Source-processor","caller":"sarama@v1.40.1/sarama.go:129","msg":"client/coordinator coordinator for service-trace-metrics-prd-osam-01 is #110 (eventbus-kafka.pl-data-lake-prd.a.intuit.com:19704)","pipeline":"osam-otlp-service-trace","vertex":"in"}
{"level":"info","ts":"2024-02-24T01:41:58.778515503Z","logger":"numaflow.Source-processor","caller":"sarama@v1.40.1/config.go:608","msg":"ClientID is the default of 'sarama', you should consider setting it to something application-specific.","pipeline":"osam-otlp-service-trace","vertex":"in"}
{"level":"info","ts":"2024-02-24T01:41:58.781396597Z","logger":"numaflow.Source-processor","caller":"sarama@v1.40.1/sarama.go:129","msg":"Connected to broker at eventbus-kafka.pl-data-lake-prd.a.intuit.com:19704 (registered as #110)","pipeline":"osam-otlp-service-trace","vertex":"in"}
panic: Kafka consumer failed with error: 
goroutine 191 [running]:
go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x1?, 0x210ca40?, {0x0?, 0x0?, 0xc0000cf680?})
	/home/runner/go/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/entry.go:198 +0x65
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0005d0c30, {0xc001e1d0c0, 0x1, 0x1})
	/home/runner/go/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/entry.go:264 +0x3ec
go.uber.org/zap.(*SugaredLogger).log(0xc000132310, 0x4, {0x25c4562?, 0x2940610?}, {0x0?, 0x0?, 0x0?}, {0xc001d95f28, 0x1, 0x1})
	/home/runner/go/pkg/mod/go.uber.org/zap@v1.24.0/sugar.go:295 +0xee
go.uber.org/zap.(*SugaredLogger).Panicw(...)
	/home/runner/go/pkg/mod/go.uber.org/zap@v1.24.0/sugar.go:235
github.com/numaproj/numaflow/pkg/sources/kafka.(*kafkaSource).startConsumer.func2()
	/home/runner/work/numaflow/numaflow/pkg/sources/kafka/reader.go:414 +0x225
created by github.com/numaproj/numaflow/pkg/sources/kafka.(*kafkaSource).startConsumer
	/home/runner/work/numaflow/numaflow/pkg/sources/kafka/reader.go:406 +0x54a
panic: Kafka consumer failed with error: 
goroutine 358 [running]:
go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x1?, 0x210ca40?, {0x0?, 0x0?, 0xc000e07420?})
	/home/runner/go/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/entry.go:198 +0x65
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc002b74ea0, {0xc0046f4500, 0x1, 0x1})
	/home/runner/go/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/entry.go:264 +0x3ec
go.uber.org/zap.(*SugaredLogger).log(0xc000491be0, 0x4, {0x25c4562?, 0x2940610?}, {0x0?, 0xc0003d4eb8?, 0xc00011df88?}, {0xc00a607f28, 0x1, 0x1})
	/home/runner/go/pkg/mod/go.uber.org/zap@v1.24.0/sugar.go:295 +0xee
go.uber.org/zap.(*SugaredLogger).Panicw(...)
	/home/runner/go/pkg/mod/go.uber.org/zap@v1.24.0/sugar.go:235
github.com/numaproj/numaflow/pkg/sources/kafka.(*kafkaSource).startConsumer.func2()
	/home/runner/work/numaflow/numaflow/pkg/sources/kafka/reader.go:414 +0x225
created by github.com/numaproj/numaflow/pkg/sources/kafka.(*kafkaSource).startConsumer
	/home/runner/work/numaflow/numaflow/pkg/sources/kafka/reader.go:406 +0x54a
{"leve


```
 
**To Reproduce**

1. ....
2. ....
3. ....

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**

- Kubernetes: [e.g. v1.18.6]
- Numaflow: [e.g. v0.5.1]

**Additional context**

---

>For quick help and support, join our [slack](https://numaproj.slack.com/join/shared_invite/zt-19svuv47m-YKHhsQ~~KK9mBv1E7pNzfg#/shared-invite/email) channel.

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.

**Comment by sarabala1979** [comment]
https://github.com/numaproj/numaflow/issues/1442
