### ISSUE TITLE
Pipeline vertices template usage make the controller enter CrashLoopBackoff

### ISSUE THREAD

**Issue by QuentinFAIDIDE** [numaproj/numaflow#1526]
**Describe the bug**
Whenever defining `spec.template.vertex`, the controller enters crashLoopBackoff with the following logs:
```
➜  ~ kubectl logs -n numaflow-system numaflow-controller-7547799c54-z4ggr 
{"level":"info","ts":"2024-02-27T09:21:39.487764989Z","logger":"numaflow.controller-manager","caller":"cmd/start.go:202","msg":"Starting controller manager","version":"Version: v1.1.4, BuildDate: 2024-01-20T22:16:46Z, GitCommit: 7ffb521bcc15612d04fe66de33d199e8c8391a7a, GitTag: v1.1.4, GitTreeState: clean, GoVersion: go1.20.12, Compiler: gc, Platform: linux/amd64"}
I0227 09:21:39.488138       1 leaderelection.go:248] attempting to acquire leader lease numaflow-system/numaflow-controller-lock...
I0227 09:21:57.921130       1 leaderelection.go:258] successfully acquired lease numaflow-system/numaflow-controller-lock
{"level":"info","ts":"2024-02-27T09:21:57.921421247Z","logger":"numaflow.autoscaler","caller":"scaling/scaling.go:404","msg":"Starting autoscaler..."}
{"level":"info","ts":"2024-02-27T09:21:57.921529557Z","logger":"numaflow.autoscaler","caller":"scaling/scaling.go:116","msg":"Started autoscaling worker 20"}
{"level":"info","ts":"2024-02-27T09:21:57.921542733Z","logger":"numaflow.autoscaler","caller":"scaling/scaling.go:116","msg":"Started autoscaling worker 5"}
{"level":"info","ts":"2024-02-27T09:21:57.921564866Z","logger":"numaflow.autoscaler","caller":"scaling/scaling.go:116","msg":"Started autoscaling worker 11"}
{"level":"info","ts":"2024-02-27T09:21:57.921544817Z","logger":"numaflow.autoscaler","caller":"scaling/scaling.go:116","msg":"Started autoscaling worker 10"}
{"level":"info","ts":"2024-02-27T09:21:57.921562952Z","logger":"numaflow.autoscaler","caller":"scaling/scaling.go:116","msg":"Started autoscaling worker 2"}
{"level":"info","ts":"2024-02-27T09:21:57.92158256Z","logger":"numaflow.autoscaler","caller":"scaling/scaling.go:116","msg":"Started autoscaling worker 4"}
{"level":"info","ts":"2024-02-27T09:21:57.921570056Z","logger":"numaflow.autoscaler","caller":"scaling/scaling.go:116","msg":"Started autoscaling worker 7"}
{"level":"info","ts":"2024-02-27T09:21:57.921627418Z","logger":"numaflow.autoscaler","caller":"scaling/scaling.go:116","msg":"Started autoscaling worker 18"}
{"level":"info","ts":"2024-02-27T09:21:57.921612408Z","logger":"numaflow.autoscaler","caller":"scaling/scaling.go:116","msg":"Started autoscaling worker 6"}
{"level":"info","ts":"2024-02-27T09:21:57.92162852Z","logger":"numaflow.autoscaler","caller":"scaling/scaling.go:116","msg":"Started autoscaling worker 8"}
{"level":"info","ts":"2024-02-27T09:21:57.92163915Z","logger":"numaflow.autoscaler","caller":"scaling/scaling.go:116","msg":"Started autoscaling worker 19"}
{"level":"info","ts":"2024-02-27T09:21:57.921645222Z","logger":"numaflow.autoscaler","caller":"scaling/scaling.go:116","msg":"Started autoscaling worker 17"}
{"level":"info","ts":"2024-02-27T09:21:57.921638299Z","logger":"numaflow.autoscaler","caller":"scaling/scaling.go:116","msg":"Started autoscaling worker 12"}
{"level":"info","ts":"2024-02-27T09:21:57.9215668Z","logger":"numaflow.autoscaler","caller":"scaling/scaling.go:116","msg":"Started autoscaling worker 3"}
{"level":"info","ts":"2024-02-27T09:21:57.921611947Z","logger":"numaflow.autoscaler","caller":"scaling/scaling.go:116","msg":"Started autoscaling worker 1"}
{"level":"info","ts":"2024-02-27T09:21:57.921595626Z","logger":"numaflow.autoscaler","caller":"scaling/scaling.go:116","msg":"Started autoscaling worker 15"}
{"level":"info","ts":"2024-02-27T09:21:57.921650953Z","logger":"numaflow.autoscaler","caller":"scaling/scaling.go:116","msg":"Started autoscaling worker 13"}
{"level":"info","ts":"2024-02-27T09:21:57.921714968Z","logger":"numaflow.autoscaler","caller":"scaling/scaling.go:116","msg":"Started autoscaling worker 9"}
{"level":"info","ts":"2024-02-27T09:21:57.921606186Z","logger":"numaflow.autoscaler","caller":"scaling/scaling.go:116","msg":"Started autoscaling worker 16"}
{"level":"info","ts":"2024-02-27T09:21:57.921731059Z","logger":"numaflow.autoscaler","caller":"scaling/scaling.go:116","msg":"Started autoscaling worker 14"}
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1b3fc10]

goroutine 604 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:119 +0x1fa
panic({0x2245cc0, 0x3b7be60})
	/opt/hostedtoolcache/go/1.20.12/x64/src/runtime/panic.go:884 +0x213
github.com/numaproj/numaflow/pkg/reconciler/vertex.(*vertexReconciler).reconcile(0xc0003dbae0, {0x294e2e8, 0xc000462b10}, 0xc001239180)
	/home/runner/work/numaflow/numaflow/pkg/reconciler/vertex/controller.go:257 +0x2990
github.com/numaproj/numaflow/pkg/reconciler/vertex.(*vertexReconciler).Reconcile(0xc0003dbae0, {0x294e2e8, 0xc0004629c0}, {{{0xc001128c40, 0xc}, {0xc000e19f50, 0x2e}}})
	/home/runner/work/numaflow/numaflow/pkg/reconciler/vertex/controller.go:75 +0x58a
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x294e2e8?, {0x294e2e8?, 0xc0004629c0?}, {{{0xc001128c40?, 0x2130a80?}, {0xc000e19f50?, 0x0?}}})
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:122 +0xc8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000991cc0, {0x294e240, 0xc0003da9b0}, {0x22f1780?, 0xc000390140?})
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:323 +0x35f
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000991cc0, {0x294e240, 0xc0003da9b0})
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:274 +0x1d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:235 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:231 +0x587
```
I only defined `nodeSelector` in the template, but trying to put only `imagePullCredentials` in the past using the pipeline wide pod template was not working either (I'm not sure if it was for the same reason, it was a long time ago).

**To Reproduce**

1. Create a pipeline with a vertex template, more specifically node selector like this:
```yaml
kind: Pipeline
apiVersion: numaflow.numaproj.io/v1alpha1
metadata:
  name: my-pipeline
  namespace: my-namespace
spec:
  templates:
    vertex:
      nodeSelector:
        mylabel: toSelect
  vertices: 
  [...]
```
If issue is sucessfully replicated, no pod or stream creating job will get created, and the numaflow controller will enter crashloopbackoff.

**Expected behavior**
Pipeline gets its pod and streams created as usual.

**Environment (please complete the following information):**

- Kubernetes: v1.26.1+k3s1
- Numaflow: v1.1.4

---

>For quick help and support, join our [slack](https://numaproj.slack.com/join/shared_invite/zt-19svuv47m-YKHhsQ~~KK9mBv1E7pNzfg#/shared-invite/email) channel.

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.

**Comment by QuentinFAIDIDE** [comment]
For those who are experiencing this issue, you can still configure everything by moving the pod template entries into the individual vertices.
```yaml
    - name: my-vertex
      partitions: 4
      udf:
        container:
          image: myimageregistry.io/myimage:v1.0.0
          env:
            - name: MY_ENV
              value: "myvalue"
      imagePullSecrets:
        - name: registry-credentials
      nodeSelector:
        mylabel: selectMe
```

**Comment by inishchith** [comment]
seems like a null check missing [right here](https://github.com/numaproj/numaflow/blob/main/pkg/reconciler/vertex/controller.go#L257)

**Comment by whynowy** [comment]
> seems like a null check missing [right here](https://github.com/numaproj/numaflow/blob/main/pkg/reconciler/vertex/controller.go#L257)

Raise a PR? @inishchith

**Comment by inishchith** [comment]
@whynowy - done. Also, can we get a patch release? 👀

**Comment by whynowy** [comment]
> @whynowy - done. Also, can we get a patch release? 👀

Absolutely!
