### ISSUE TITLE
User defined source: unable to crash  the pod by propagating error

### ISSUE THREAD

**Issue by nagarajatantry** [numaproj/numaflow#1592]
**Describe the bug**
I am writing a user defined source using numaflow-java SDK to consume from Kafka topic.  My kafka consumer runs on a separate thread. If it fails to consume, I want the main thread to stop and the pod to crash.  To do so, in the `read` method, I check whether the consumer thread is alive. if not, I raise a RuntimeException expecting that the pod will crash.  But the `read` method keeps getting called 

Code Snippet
```java
public class CustomSource extends Sourcer {
      private final Thread messageConsumerThread;

     public CustomSource() {
       // initialize consumer thread... 
        messageConsumerThread.start()
     }
     
      public void read(ReadRequest readRequest, OutputObserver outputObserver) {
        //check if consumer thread is still alive
            if (!messageConsumerThread.isAlive()) {
                 throw new RuntimeException(String.format(
                    "thread:%s that consumes message from the topic is terminated.", messageConsumerThread.getName()));
           }
      }
}
```

Exception Stacktrace:
```
[2024-03-22T15:41:36,963+0000]-[INFO ]-["grpc-default-executor-6"  cid=, clu=]-[c.i.o.n.c.EventbusSource]-[35]-i am in read
Mar 22, 2024 3:41:36 PM io.grpc.internal.SerializingExecutor run
SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed@15e432f9
java.lang.RuntimeException: thread:Thread-0 that consumes message from the topic is terminated.
	at com.intuit.ossanalytics.numaflow.consumer.EventbusSource.read(EventbusSource.java:38)
	at io.numaproj.numaflow.sourcer.Service.readFn(Service.java:47)
	at io.numaproj.numaflow.source.v1.SourceGrpc$MethodHandlers.invoke(SourceGrpc.java:530)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at io.numaproj.numaflow.shared.GrpcServerUtils$1$1.onHalfClose(GrpcServerUtils.java:126)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:351)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:860)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

[2024-03-22T15:41:36,964+0000]-[INFO ]-["grpc-default-executor-6"  cid=, clu=]-[c.i.o.n.c.EventbusSource]-[35]-i am in read
Mar 22, 2024 3:41:36 PM io.grpc.internal.SerializingExecutor run
SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed@2b761321
java.lang.RuntimeException: thread:Thread-0 that consumes message from the topic is terminated.
	at com.intuit.ossanalytics.numaflow.consumer.EventbusSource.read(EventbusSource.java:38)
	at io.numaproj.numaflow.sourcer.Service.readFn(Service.java:47)
	at io.numaproj.numaflow.source.v1.SourceGrpc$MethodHandlers.invoke(SourceGrpc.java:530)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at io.numaproj.numaflow.shared.GrpcServerUtils$1$1.onHalfClose(GrpcServerUtils.java:126)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:351)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:860)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

- Kubernetes: `v1.26.13`
- Numaflow: `v1.1.7`

**Comment by yhl25** [comment]
We can exit the udsource container using `System.exit(1)`, but we need to think through the impact.
```
[netty-boss] WARN io.netty.bootstrap.ServerBootstrap - Unknown channel option 'SO_KEEPALIVE' for channel '[id: 0x4a4f2bde, L:/var/run/numaflow/source.sock - R:]'
java.lang.RuntimeException: No more messages to read
	at io.numaproj.numaflow.examples.source.simple.SimpleSource.read(SimpleSource.java:58)
	at io.numaproj.numaflow.sourcer.Service.readFn(Service.java:47)
	at io.numaproj.numaflow.source.v1.SourceGrpc$MethodHandlers.invoke(SourceGrpc.java:530)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at io.numaproj.numaflow.shared.GrpcServerUtils$1$1.onHalfClose(GrpcServerUtils.java:126)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:351)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:860)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
*** shutting down gRPC server since JVM is shutting down
[netty-boss] WARN io.netty.bootstrap.ServerBootstrap - Unknown channel option 'SO_KEEPALIVE' for channel '[id: 0xad78c3f1, L:/var/run/numaflow/source.sock - R:]'
java.lang.RuntimeException: No more messages to read
	at io.numaproj.numaflow.examples.source.simple.SimpleSource.read(SimpleSource.java:58)
	at io.numaproj.numaflow.sourcer.Service.readFn(Service.java:47)
	at io.numaproj.numaflow.source.v1.SourceGrpc$MethodHandlers.invoke(SourceGrpc.java:530)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at io.numaproj.numaflow.shared.GrpcServerUtils$1$1.onHalfClose(GrpcServerUtils.java:126)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:351)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:860)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
*** shutting down gRPC server since JVM is shutting down
{"level":"warn","ts":"2024-03-25T17:04:12.570167746Z","logger":"numaflow.Source-processor","caller":"forward/data_forward.go:206","msg":"failed to read from source","pipeline":"java-pipeline","vertex":"in","error":"failed to read messages from udsource: rpc error: code = Unknown desc = No more messages to read"}
[netty-boss] WARN io.netty.bootstrap.ServerBootstrap - Unknown channel option 'SO_KEEPALIVE' for channel '[id: 0xb3d24a54, L:/var/run/numaflow/source.sock - R:]'
java.lang.RuntimeException: No more messages to read
	at io.numaproj.numaflow.examples.source.simple.SimpleSource.read(SimpleSource.java:58)
	at io.numaproj.numaflow.sourcer.Service.readFn(Service.java:47)
	at io.numaproj.numaflow.source.v1.SourceGrpc$MethodHandlers.invoke(SourceGrpc.java:530)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at io.numaproj.numaflow.shared.GrpcServerUtils$1$1.onHalfClose(GrpcServerUtils.java:126)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:351)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:860)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
*** shutting down gRPC server since JVM is shutting down
[netty-boss] WARN io.netty.bootstrap.ServerBootstrap - Unknown channel option 'SO_KEEPALIVE' for channel '[id: 0xb6ae7b4c, L:/var/run/numaflow/source.sock - R:]'
java.lang.RuntimeException: No more messages to read
	at io.numaproj.numaflow.examples.source.simple.SimpleSource.read(SimpleSource.java:58)
	at io.numaproj.numaflow.sourcer.Service.readFn(Service.java:47)
	at io.numaproj.numaflow.source.v1.SourceGrpc$MethodHandlers.invoke(SourceGrpc.java:530)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at io.numaproj.numaflow.shared.GrpcServerUtils$1$1.onHalfClose(GrpcServerUtils.java:126)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:351)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:860)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
*** shutting down gRPC server since JVM is shutting down
[netty-boss] WARN io.netty.bootstrap.ServerBootstrap - Unknown channel option 'SO_KEEPALIVE' for channel '[id: 0xe9607337, L:/var/run/numaflow/source.sock - R:]'
java.lang.RuntimeException: No more messages to read
	at io.numaproj.numaflow.examples.source.simple.SimpleSource.read(SimpleSource.java:58)
	at io.numaproj.numaflow.sourcer.Service.readFn(Service.java:47)
	at io.numaproj.numaflow.source.v1.SourceGrpc$MethodHandlers.invoke(SourceGrpc.java:530)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at io.numaproj.numaflow.shared.GrpcServerUtils$1$1.onHalfClose(GrpcServerUtils.java:126)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:351)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:860)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
*** shutting down gRPC server since JVM is shutting down
[main] INFO io.numaproj.numaflow.shared.GrpcServerUtils - Writing server info io.numaproj.numaflow.info.ServerInfo@63e2203c to /var/run/numaflow/sourcer-server-info
[main] INFO io.numaproj.numaflow.sourcer.Server - Server started, listening on socket path: /var/run/numaflow/source.sock
[netty-boss] WARN io.netty.bootstrap.ServerBootstrap - Unknown channel option 'SO_KEEPALIVE' for channel '[id: 0xb6ead60d, L:/var/run/numaflow/source.sock - R:]'
java.lang.RuntimeException: No more messages to read
	at io.numaproj.numaflow.examples.source.simple.SimpleSource.read(SimpleSource.java:58)
	at io.numaproj.numaflow.sourcer.Service.readFn(Service.java:47)
	at io.numaproj.numaflow.source.v1.SourceGrpc$MethodHandlers.invoke(SourceGrpc.java:530)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at io.numaproj.numaflow.shared.GrpcServerUtils$1$1.onHalfClose(GrpcServerUtils.java:126)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:351)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:860)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
*** shutting down gRPC server since JVM is shutting down
[main] INFO io.numaproj.numaflow.shared.GrpcServerUtils - Writing server info io.numaproj.numaflow.info.ServerInfo@63e2203c to /var/run/numaflow/sourcer-server-info
[main] INFO io.numaproj.numaflow.sourcer.Server - Server started, listening on socket path: /var/run/numaflow/source.sock
[netty-boss] WARN io.netty.bootstrap.ServerBootstrap - Unknown channel option 'SO_KEEPALIVE' for channel '[id: 0xaa20a710, L:/var/run/numaflow/source.sock - R:]'
java.lang.RuntimeException: No more messages to read
	at io.numaproj.numaflow.examples.source.simple.SimpleSource.read(SimpleSource.java:58)
	at io.numaproj.numaflow.sourcer.Service.readFn(Service.java:47)
	at io.numaproj.numaflow.source.v1.SourceGrpc$MethodHandlers.invoke(SourceGrpc.java:530)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at io.numaproj.numaflow.shared.GrpcServerUtils$1$1.onHalfClose(GrpcServerUtils.java:126)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:351)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:860)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
*** shutting down gRPC server since JVM is shutting down
[main] INFO io.numaproj.numaflow.shared.GrpcServerUtils - Writing server info io.numaproj.numaflow.info.ServerInfo@63e2203c to /var/run/numaflow/sourcer-server-info
[main] INFO io.numaproj.numaflow.sourcer.Server - Server started, listening on socket path: /var/run/numaflow/source.sock
[netty-boss] WARN io.netty.bootstrap.ServerBootstrap - Unknown channel option 'SO_KEEPALIVE' for channel '[id: 0xc8c22612, L:/var/run/numaflow/source.sock - R:]'
java.lang.RuntimeException: No more messages to read
	at io.numaproj.numaflow.examples.source.simple.SimpleSource.read(SimpleSource.java:58)
	at io.numaproj.numaflow.sourcer.Service.readFn(Service.java:47)
	at io.numaproj.numaflow.source.v1.SourceGrpc$MethodHandlers.invoke(SourceGrpc.java:530)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at io.numaproj.numaflow.shared.GrpcServerUtils$1$1.onHalfClose(GrpcServerUtils.java:126)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:351)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:860)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
*** shutting down gRPC server since JVM is shutting down
[main] INFO io.numaproj.numaflow.shared.GrpcServerUtils - Writing server info io.numaproj.numaflow.info.ServerInfo@63e2203c to /var/run/numaflow/sourcer-server-info
[main] INFO io.numaproj.numaflow.sourcer.Server - Server started, listening on socket path: /var/run/numaflow/source.sock
[netty-boss] WARN io.netty.bootstrap.ServerBootstrap - Unknown channel option 'SO_KEEPALIVE' for channel '[id: 0xf5a023c7, L:/var/run/numaflow/source.sock - R:]'
java.lang.RuntimeException: No more messages to read
	at io.numaproj.numaflow.examples.source.simple.SimpleSource.read(SimpleSource.java:58)
	at io.numaproj.numaflow.sourcer.Service.readFn(Service.java:47)
	at io.numaproj.numaflow.source.v1.SourceGrpc$MethodHandlers.invoke(SourceGrpc.java:530)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at io.numaproj.numaflow.shared.GrpcServerUtils$1$1.onHalfClose(GrpcServerUtils.java:126)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:351)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:860)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
*** shutting down gRPC server since JVM is shutting down
[main] INFO io.numaproj.numaflow.shared.GrpcServerUtils - Writing server info io.numaproj.numaflow.info.ServerInfo@63e2203c to /var/run/numaflow/sourcer-server-info
[main] INFO io.numaproj.numaflow.sourcer.Server - Server started, listening on socket path: /var/run/numaflow/source.sock
[netty-boss] WARN io.netty.bootstrap.ServerBootstrap - Unknown channel option 'SO_KEEPALIVE' for channel '[id: 0x06b0e283, L:/var/run/numaflow/source.sock - R:]'
java.lang.RuntimeException: No more messages to read
	at io.numaproj.numaflow.examples.source.simple.SimpleSource.read(SimpleSource.java:58)
	at io.numaproj.numaflow.sourcer.Service.readFn(Service.java:47)
	at io.numaproj.numaflow.source.v1.SourceGrpc$MethodHandlers.invoke(SourceGrpc.java:530)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at io.numaproj.numaflow.shared.GrpcServerUtils$1$1.onHalfClose(GrpcServerUtils.java:126)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:351)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:860)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
*** shutting down gRPC server since JVM is shutting down
{"level":"warn","ts":"2024-03-25T16:28:34.418477103Z","logger":"numaflow.Source-processor","caller":"forward/data_forward.go:206","msg":"failed to read from source","pipeline":"java-pipeline","vertex":"in","error":"failed to read messages from udsource: rpc error: code = Unknown desc = No more messages to read"}
{"level":"warn","ts":"2024-03-25T16:28:31.379548081Z","logger":"numaflow.Source-processor","caller":"forward/data_forward.go:206","msg":"failed to read from source","pipeline":"java-pipeline","vertex":"in","error":"failed to read messages from udsource: rpc error: code = Unknown desc = No more messages to read"}

```
