### ISSUE TITLE
Restart monovertex on UDF errors

### ISSUE THREAD

**Issue by vigith** [numaproj/numaflow#2206]

**Comment by yhl25** [comment]
I verified the UDF errors in Monovertex, and it is shutting down gracefully. We do not need to make any changes.

#### Source 

```
2024-11-06T16:31:35.734189Z  INFO numaflow_core: Starting monovertex forwarder with config: MonovertexConfig { name: "transformer-mono-vertex", batch_size: 500, read_timeout: 1s, replica: 0, source_config: SourceConfig { source_type: UserDefined(UserDefinedConfig { grpc_max_message_size: 67108864, socket_path: "/var/run/numaflow/source.sock", server_info_path: "/var/run/numaflow/sourcer-server-info" }) }, sink_config: SinkConfig { sink_type: UserDefined(UserDefinedConfig { grpc_max_message_size: 67108864, socket_path: "/var/run/numaflow/sink.sock", server_info_path: "/var/run/numaflow/sinker-server-info" }), retry_config: Some(RetryConfig { sink_max_retry_attempts: 65535, sink_retry_interval_in_ms: 1, sink_retry_on_fail_strategy: Retry, sink_default_retry_strategy: RetryStrategy { backoff: Some(Backoff { interval: Some(1ms), steps: Some(65535) }), on_failure: Some("retry") } }) }, transformer_config: Some(TransformerConfig { transformer_type: UserDefined(UserDefinedConfig { grpc_max_message_size: 67108864, socket_path: "/var/run/numaflow/sourcetransform.sock", server_info_path: "/var/run/numaflow/sourcetransformer-server-info" }) }), fb_sink_config: None, metrics_config: MetricsConfig { metrics_server_listen_port: 2469, lag_check_interval_in_secs: 5, lag_refresh_interval_in_secs: 3 } }
2024-11-06T16:31:35.734248Z  INFO numaflow_core::shared::server_info: Server info file: ServerInfo { protocol: "uds", language: "go", minimum_numaflow_version: "1.3.1-z", version: "v0.8.1", metadata: None }
2024-11-06T16:31:35.734255Z  INFO numaflow_core::shared::server_info: Version_info: VersionInfo { version: "latest+unknown", build_date: "1970-01-01T00:00:00Z", git_commit: "", git_tag: "", git_tree_state: "", go_version: "unknown", compiler: "", platform: "linux/aarch64" }
2024-11-06T16:31:36.736461Z  INFO numaflow_core::shared::utils: Waiting for source client to be ready...
2024-11-06T16:31:36.737933Z  INFO numaflow_core::shared::server_info: Server info file: ServerInfo { protocol: "uds", language: "go", minimum_numaflow_version: "1.3.1-z", version: "v0.8.1", metadata: None }
2024-11-06T16:31:36.737955Z  INFO numaflow_core::shared::server_info: Version_info: VersionInfo { version: "latest+unknown", build_date: "1970-01-01T00:00:00Z", git_commit: "", git_tag: "", git_tree_state: "", go_version: "unknown", compiler: "", platform: "linux/aarch64" }
2024-11-06T16:31:38.744178Z  INFO numaflow_core::shared::server_info: Server info file: ServerInfo { protocol: "uds", language: "go", minimum_numaflow_version: "1.3.1-z", version: "v0.8.1", metadata: None }
2024-11-06T16:31:38.744199Z  INFO numaflow_core::shared::server_info: Version_info: VersionInfo { version: "latest+unknown", build_date: "1970-01-01T00:00:00Z", git_commit: "", git_tag: "", git_tree_state: "", go_version: "unknown", compiler: "", platform: "linux/aarch64" }
2024-11-06T16:31:38.747237Z  INFO numaflow_core::monovertex::forwarder: Forwarder has started
2024-11-06T16:31:38.751097Z  INFO numaflow_core::metrics: Stopped the Lag-Reader Expose and Builder tasks
2024-11-06T16:31:38.751116Z ERROR numaflow_core: Application error running monovertex: Forwarder("Failed to read messages from source Grpc(\"status: Unknown, message: \\\"panic inside source handler: Not a valid source\\\", details: [], metadata: MetadataMap { headers: {} }\")")
2024-11-06T16:31:38.751121Z  INFO numaflow_core: Gracefully Exiting...
```


#### Transformer

```
2024-11-06T16:35:02.664172Z  INFO numaflow_core: Starting monovertex forwarder with config: MonovertexConfig { name: "transformer-mono-vertex", batch_size: 500, read_timeout: 1s, replica: 0, source_config: SourceConfig { source_type: UserDefined(UserDefinedConfig { grpc_max_message_size: 67108864, socket_path: "/var/run/numaflow/source.sock", server_info_path: "/var/run/numaflow/sourcer-server-info" }) }, sink_config: SinkConfig { sink_type: UserDefined(UserDefinedConfig { grpc_max_message_size: 67108864, socket_path: "/var/run/numaflow/sink.sock", server_info_path: "/var/run/numaflow/sinker-server-info" }), retry_config: Some(RetryConfig { sink_max_retry_attempts: 65535, sink_retry_interval_in_ms: 1, sink_retry_on_fail_strategy: Retry, sink_default_retry_strategy: RetryStrategy { backoff: Some(Backoff { interval: Some(1ms), steps: Some(65535) }), on_failure: Some("retry") } }) }, transformer_config: Some(TransformerConfig { transformer_type: UserDefined(UserDefinedConfig { grpc_max_message_size: 67108864, socket_path: "/var/run/numaflow/sourcetransform.sock", server_info_path: "/var/run/numaflow/sourcetransformer-server-info" }) }), fb_sink_config: None, metrics_config: MetricsConfig { metrics_server_listen_port: 2469, lag_check_interval_in_secs: 5, lag_refresh_interval_in_secs: 3 } }
2024-11-06T16:35:02.664229Z  INFO numaflow_core::shared::server_info: Server info file: ServerInfo { protocol: "uds", language: "go", minimum_numaflow_version: "1.3.1-z", version: "v0.8.1", metadata: None }
2024-11-06T16:35:02.664236Z  INFO numaflow_core::shared::server_info: Version_info: VersionInfo { version: "latest+unknown", build_date: "1970-01-01T00:00:00Z", git_commit: "", git_tag: "", git_tree_state: "", go_version: "unknown", compiler: "", platform: "linux/aarch64" }
2024-11-06T16:35:04.667325Z  INFO numaflow_core::shared::utils: Waiting for source client to be ready...
2024-11-06T16:35:04.667854Z  INFO numaflow_core::shared::server_info: Server info file: ServerInfo { protocol: "uds", language: "go", minimum_numaflow_version: "1.3.1-z", version: "v0.8.1", metadata: None }
2024-11-06T16:35:04.667866Z  INFO numaflow_core::shared::server_info: Version_info: VersionInfo { version: "latest+unknown", build_date: "1970-01-01T00:00:00Z", git_commit: "", git_tag: "", git_tree_state: "", go_version: "unknown", compiler: "", platform: "linux/aarch64" }
2024-11-06T16:35:05.671010Z  INFO numaflow_core::shared::server_info: Server info file: ServerInfo { protocol: "uds", language: "go", minimum_numaflow_version: "1.3.1-z", version: "v0.8.1", metadata: None }
2024-11-06T16:35:05.671028Z  INFO numaflow_core::shared::server_info: Version_info: VersionInfo { version: "latest+unknown", build_date: "1970-01-01T00:00:00Z", git_commit: "", git_tag: "", git_tree_state: "", go_version: "unknown", compiler: "", platform: "linux/aarch64" }
2024-11-06T16:35:05.673350Z  INFO numaflow_core::monovertex::forwarder: Forwarder has started
2024-11-06T16:35:05.677478Z  INFO numaflow_core::metrics: Stopped the Lag-Reader Expose and Builder tasks
2024-11-06T16:35:05.677485Z ERROR numaflow_core: Application error running monovertex: Forwarder("Failed to apply transformation to messages Transformer(\"gRPC error while receiving messages from source transformer server: Status { code: Internal, message: \\\"transformer function panicked\\\", source: None }\")")
2024-11-06T16:35:05.677488Z  INFO numaflow_core: Gracefully Exiting...
```

#### Sink
```
2024-11-06T16:38:21.205907Z  INFO numaflow_core: Starting monovertex forwarder with config: MonovertexConfig { name: "transformer-mono-vertex", batch_size: 500, read_timeout: 1s, replica: 0, source_config: SourceConfig { source_type: UserDefined(UserDefinedConfig { grpc_max_message_size: 67108864, socket_path: "/var/run/numaflow/source.sock", server_info_path: "/var/run/numaflow/sourcer-server-info" }) }, sink_config: SinkConfig { sink_type: UserDefined(UserDefinedConfig { grpc_max_message_size: 67108864, socket_path: "/var/run/numaflow/sink.sock", server_info_path: "/var/run/numaflow/sinker-server-info" }), retry_config: Some(RetryConfig { sink_max_retry_attempts: 65535, sink_retry_interval_in_ms: 1, sink_retry_on_fail_strategy: Retry, sink_default_retry_strategy: RetryStrategy { backoff: Some(Backoff { interval: Some(1ms), steps: Some(65535) }), on_failure: Some("retry") } }) }, transformer_config: Some(TransformerConfig { transformer_type: UserDefined(UserDefinedConfig { grpc_max_message_size: 67108864, socket_path: "/var/run/numaflow/sourcetransform.sock", server_info_path: "/var/run/numaflow/sourcetransformer-server-info" }) }), fb_sink_config: None, metrics_config: MetricsConfig { metrics_server_listen_port: 2469, lag_check_interval_in_secs: 5, lag_refresh_interval_in_secs: 3 } }
2024-11-06T16:38:21.205954Z  INFO numaflow_core::shared::server_info: Server info file "/var/run/numaflow/sourcer-server-info" is not ready, waiting...
2024-11-06T16:38:22.208235Z  INFO numaflow_core::shared::server_info: Server info file "/var/run/numaflow/sourcer-server-info" is not ready, waiting...
2024-11-06T16:38:23.210305Z  INFO numaflow_core::shared::server_info: Server info file: ServerInfo { protocol: "uds", language: "go", minimum_numaflow_version: "1.3.1-z", version: "v0.8.1", metadata: None }
2024-11-06T16:38:23.210383Z  INFO numaflow_core::shared::server_info: Version_info: VersionInfo { version: "latest+unknown", build_date: "1970-01-01T00:00:00Z", git_commit: "", git_tag: "", git_tree_state: "", go_version: "unknown", compiler: "", platform: "linux/aarch64" }
2024-11-06T16:38:23.210855Z  INFO numaflow_core::shared::utils: Waiting for source client to be ready...
2024-11-06T16:38:23.212233Z  INFO numaflow_core::shared::server_info: Server info file "/var/run/numaflow/sinker-server-info" is not ready, waiting...
2024-11-06T16:38:24.213529Z  INFO numaflow_core::shared::server_info: Server info file: ServerInfo { protocol: "uds", language: "go", minimum_numaflow_version: "1.3.1-z", version: "v0.8.1", metadata: None }
2024-11-06T16:38:24.213550Z  INFO numaflow_core::shared::server_info: Version_info: VersionInfo { version: "latest+unknown", build_date: "1970-01-01T00:00:00Z", git_commit: "", git_tag: "", git_tree_state: "", go_version: "unknown", compiler: "", platform: "linux/aarch64" }
2024-11-06T16:38:24.214357Z  INFO numaflow_core::shared::server_info: Server info file: ServerInfo { protocol: "uds", language: "go", minimum_numaflow_version: "1.3.1-z", version: "v0.8.1", metadata: None }
2024-11-06T16:38:24.214374Z  INFO numaflow_core::shared::server_info: Version_info: VersionInfo { version: "latest+unknown", build_date: "1970-01-01T00:00:00Z", git_commit: "", git_tag: "", git_tree_state: "", go_version: "unknown", compiler: "", platform: "linux/aarch64" }
2024-11-06T16:38:24.217121Z  INFO numaflow_core::monovertex::forwarder: Forwarder has started
2024-11-06T16:38:24.262155Z  INFO numaflow_core::metrics: Stopped the Lag-Reader Expose and Builder tasks
2024-11-06T16:38:24.264734Z ERROR numaflow_core: Application error running monovertex: Forwarder("Failed to write messages to sink Grpc(\"status: Unknown, message: \\\"panic inside sink handler: Not a valid message\\\", details: [], metadata: MetadataMap { headers: {} }\")")
2024-11-06T16:38:24.264807Z  INFO numaflow_core: Gracefully Exiting...
```

**Comment by KeranYang** [comment]
For Java.

**transformer**

```
2024-11-06T22:50:53.095350Z  INFO numaflow_core: Starting monovertex forwarder with config: MonovertexConfig { name: "transformer-mono-vertex", batch_size: 500, read_timeout: 1s, replica: 0, source_config: SourceConfig { source_type: UserDefined(UserDefinedConfig { grpc_max_message_size: 67108864, socket_path: "/var/run/numaflow/source.sock", server_info_path: "/var/run/numaflow/sourcer-server-info" }) }, sink_config: SinkConfig { sink_type: UserDefined(UserDefinedConfig { grpc_max_message_size: 67108864, socket_path: "/var/run/numaflow/sink.sock", server_info_path: "/var/run/numaflow/sinker-server-info" }), retry_config: Some(RetryConfig { sink_max_retry_attempts: 65535, sink_retry_interval_in_ms: 1, sink_retry_on_fail_strategy: Retry, sink_default_retry_strategy: RetryStrategy { backoff: Some(Backoff { interval: Some(1ms), steps: Some(65535) }), on_failure: Some("retry") } }) }, transformer_config: Some(TransformerConfig { transformer_type: UserDefined(UserDefinedConfig { grpc_max_message_size: 67108864, socket_path: "/var/run/numaflow/sourcetransform.sock", server_info_path: "/var/run/numaflow/sourcetransformer-server-info" }) }), fb_sink_config: None, metrics_config: MetricsConfig { metrics_server_listen_port: 2469, lag_check_interval_in_secs: 5, lag_refresh_interval_in_secs: 3 } }
2024-11-06T22:50:53.095644Z  INFO numaflow_core::shared::server_info: Server info file: ServerInfo { protocol: "uds", language: "java", minimum_numaflow_version: "1.3.1-z", version: "0.8.0", metadata: Some({}) }
2024-11-06T22:50:53.095671Z  INFO numaflow_core::shared::server_info: Version_info: VersionInfo { version: "latest+unknown", build_date: "1970-01-01T00:00:00Z", git_commit: "", git_tag: "", git_tree_state: "", go_version: "unknown", compiler: "", platform: "linux/aarch64" }
2024-11-06T22:50:53.096732Z  INFO numaflow_core::shared::utils: Waiting for source client to be ready...
2024-11-06T22:50:54.340094Z  INFO numaflow_core::shared::server_info: Server info file: ServerInfo { protocol: "uds", language: "java", minimum_numaflow_version: "1.3.1-z", version: "0.8.0", metadata: Some({}) }
2024-11-06T22:50:54.340115Z  INFO numaflow_core::shared::server_info: Version_info: VersionInfo { version: "latest+unknown", build_date: "1970-01-01T00:00:00Z", git_commit: "", git_tag: "", git_tree_state: "", go_version: "unknown", compiler: "", platform: "linux/aarch64" }
2024-11-06T22:50:55.481699Z  INFO numaflow_core::shared::server_info: Server info file: ServerInfo { protocol: "uds", language: "java", minimum_numaflow_version: "1.3.1-z", version: "0.8.0", metadata: Some({}) }
2024-11-06T22:50:55.481734Z  INFO numaflow_core::shared::server_info: Version_info: VersionInfo { version: "latest+unknown", build_date: "1970-01-01T00:00:00Z", git_commit: "", git_tag: "", git_tree_state: "", go_version: "unknown", compiler: "", platform: "linux/aarch64" }
2024-11-06T22:50:56.662406Z  INFO numaflow_core::monovertex::forwarder: Forwarder has started
2024-11-06T22:50:58.404047Z  INFO numaflow_core::metrics: Stopped the Lag-Reader Expose and Builder tasks
2024-11-06T22:50:58.404144Z ERROR numaflow_core: Application error running monovertex: Forwarder("Failed to apply transformation to messages Transformer(\"gRPC error while receiving messages from source transformer server: Status { code: Internal, message: \\\"This is a test exception\\\", source: None }\")")
2024-11-06T22:50:58.404149Z  INFO numaflow_core: Gracefully Exiting...
```

**sink**

```
2024-11-06T22:54:23.657978Z  INFO numaflow_core: Starting monovertex forwarder with config: MonovertexConfig { name: "transformer-mono-vertex", batch_size: 500, read_timeout: 1s, replica: 0, source_config: SourceConfig { source_type: UserDefined(UserDefinedConfig { grpc_max_message_size: 67108864, socket_path: "/var/run/numaflow/source.sock", server_info_path: "/var/run/numaflow/sourcer-server-info" }) }, sink_config: SinkConfig { sink_type: UserDefined(UserDefinedConfig { grpc_max_message_size: 67108864, socket_path: "/var/run/numaflow/sink.sock", server_info_path: "/var/run/numaflow/sinker-server-info" }), retry_config: Some(RetryConfig { sink_max_retry_attempts: 65535, sink_retry_interval_in_ms: 1, sink_retry_on_fail_strategy: Retry, sink_default_retry_strategy: RetryStrategy { backoff: Some(Backoff { interval: Some(1ms), steps: Some(65535) }), on_failure: Some("retry") } }) }, transformer_config: Some(TransformerConfig { transformer_type: UserDefined(UserDefinedConfig { grpc_max_message_size: 67108864, socket_path: "/var/run/numaflow/sourcetransform.sock", server_info_path: "/var/run/numaflow/sourcetransformer-server-info" }) }), fb_sink_config: None, metrics_config: MetricsConfig { metrics_server_listen_port: 2469, lag_check_interval_in_secs: 5, lag_refresh_interval_in_secs: 3 } }
2024-11-06T22:54:23.658257Z  INFO numaflow_core::shared::server_info: Server info file: ServerInfo { protocol: "uds", language: "java", minimum_numaflow_version: "1.3.1-z", version: "0.8.0", metadata: Some({}) }
2024-11-06T22:54:23.658306Z  INFO numaflow_core::shared::server_info: Version_info: VersionInfo { version: "latest+unknown", build_date: "1970-01-01T00:00:00Z", git_commit: "", git_tag: "", git_tree_state: "", go_version: "unknown", compiler: "", platform: "linux/aarch64" }
2024-11-06T22:54:23.658923Z  INFO numaflow_core::shared::utils: Waiting for source client to be ready...
2024-11-06T22:54:24.904633Z  INFO numaflow_core::shared::server_info: Server info file: ServerInfo { protocol: "uds", language: "java", minimum_numaflow_version: "1.3.1-z", version: "0.8.0", metadata: Some({}) }
2024-11-06T22:54:24.904658Z  INFO numaflow_core::shared::server_info: Version_info: VersionInfo { version: "latest+unknown", build_date: "1970-01-01T00:00:00Z", git_commit: "", git_tag: "", git_tree_state: "", go_version: "unknown", compiler: "", platform: "linux/aarch64" }
2024-11-06T22:54:28.795446Z  INFO numaflow_core::shared::server_info: Server info file: ServerInfo { protocol: "uds", language: "java", minimum_numaflow_version: "1.3.1-z", version: "0.8.0", metadata: Some({}) }
2024-11-06T22:54:28.795475Z  INFO numaflow_core::shared::server_info: Version_info: VersionInfo { version: "latest+unknown", build_date: "1970-01-01T00:00:00Z", git_commit: "", git_tag: "", git_tree_state: "", go_version: "unknown", compiler: "", platform: "linux/aarch64" }
2024-11-06T22:54:29.094374Z  INFO numaflow_core::monovertex::forwarder: Forwarder has started
2024-11-06T22:54:31.502167Z  INFO numaflow_core::metrics: Stopped the Lag-Reader Expose and Builder tasks
2024-11-06T22:54:31.502200Z ERROR numaflow_core: Application error running monovertex: Forwarder("Failed to write messages to sink Grpc(\"status: Internal, message: \\\"java.lang.RuntimeException: This is a test exception\\\", details: [], metadata: MetadataMap { headers: {} }\")")
2024-11-06T22:54:31.502203Z  INFO numaflow_core: Gracefully Exiting...
```

**source**

```
2024-11-06T22:57:04.186529Z  INFO numaflow_core: Starting monovertex forwarder with config: MonovertexConfig { name: "transformer-mono-vertex", batch_size: 500, read_timeout: 1s, replica: 0, source_config: SourceConfig { source_type: UserDefined(UserDefinedConfig { grpc_max_message_size: 67108864, socket_path: "/var/run/numaflow/source.sock", server_info_path: "/var/run/numaflow/sourcer-server-info" }) }, sink_config: SinkConfig { sink_type: UserDefined(UserDefinedConfig { grpc_max_message_size: 67108864, socket_path: "/var/run/numaflow/sink.sock", server_info_path: "/var/run/numaflow/sinker-server-info" }), retry_config: Some(RetryConfig { sink_max_retry_attempts: 65535, sink_retry_interval_in_ms: 1, sink_retry_on_fail_strategy: Retry, sink_default_retry_strategy: RetryStrategy { backoff: Some(Backoff { interval: Some(1ms), steps: Some(65535) }), on_failure: Some("retry") } }) }, transformer_config: Some(TransformerConfig { transformer_type: UserDefined(UserDefinedConfig { grpc_max_message_size: 67108864, socket_path: "/var/run/numaflow/sourcetransform.sock", server_info_path: "/var/run/numaflow/sourcetransformer-server-info" }) }), fb_sink_config: None, metrics_config: MetricsConfig { metrics_server_listen_port: 2469, lag_check_interval_in_secs: 5, lag_refresh_interval_in_secs: 3 } }
2024-11-06T22:57:04.186962Z  INFO numaflow_core::shared::server_info: Server info file: ServerInfo { protocol: "uds", language: "java", minimum_numaflow_version: "1.3.1-z", version: "0.8.0", metadata: Some({}) }
2024-11-06T22:57:04.187004Z  INFO numaflow_core::shared::server_info: Version_info: VersionInfo { version: "latest+unknown", build_date: "1970-01-01T00:00:00Z", git_commit: "", git_tag: "", git_tree_state: "", go_version: "unknown", compiler: "", platform: "linux/aarch64" }
2024-11-06T22:57:09.196273Z ERROR numaflow_core: Application error running monovertex: Connection("Failed to connect: tonic::transport::Error(Transport, ConnectError(Os { code: 2, kind: NotFound, message: \"No such file or directory\" }))")
2024-11-06T22:57:09.196406Z  INFO numaflow_core: Gracefully Exiting...
2024-11-06T22:57:38.087498Z  INFO numaflow_core: Starting monovertex forwarder with config: MonovertexConfig { name: "transformer-mono-vertex", batch_size: 500, read_timeout: 1s, replica: 0, source_config: SourceConfig { source_type: UserDefined(UserDefinedConfig { grpc_max_message_size: 67108864, socket_path: "/var/run/numaflow/source.sock", server_info_path: "/var/run/numaflow/sourcer-server-info" }) }, sink_config: SinkConfig { sink_type: UserDefined(UserDefinedConfig { grpc_max_message_size: 67108864, socket_path: "/var/run/numaflow/sink.sock", server_info_path: "/var/run/numaflow/sinker-server-info" }), retry_config: Some(RetryConfig { sink_max_retry_attempts: 65535, sink_retry_interval_in_ms: 1, sink_retry_on_fail_strategy: Retry, sink_default_retry_strategy: RetryStrategy { backoff: Some(Backoff { interval: Some(1ms), steps: Some(65535) }), on_failure: Some("retry") } }) }, transformer_config: Some(TransformerConfig { transformer_type: UserDefined(UserDefinedConfig { grpc_max_message_size: 67108864, socket_path: "/var/run/numaflow/sourcetransform.sock", server_info_path: "/var/run/numaflow/sourcetransformer-server-info" }) }), fb_sink_config: None, metrics_config: MetricsConfig { metrics_server_listen_port: 2469, lag_check_interval_in_secs: 5, lag_refresh_interval_in_secs: 3 } }
2024-11-06T22:57:38.087794Z  INFO numaflow_core::shared::server_info: Server info file: ServerInfo { protocol: "uds", language: "java", minimum_numaflow_version: "1.3.1-z", version: "0.8.0", metadata: Some({}) }
2024-11-06T22:57:38.087824Z  INFO numaflow_core::shared::server_info: Version_info: VersionInfo { version: "latest+unknown", build_date: "1970-01-01T00:00:00Z", git_commit: "", git_tag: "", git_tree_state: "", go_version: "unknown", compiler: "", platform: "linux/aarch64" }
2024-11-06T22:57:38.088996Z  INFO numaflow_core::shared::utils: Waiting for source client to be ready...
2024-11-06T22:57:39.350458Z  INFO numaflow_core::shared::server_info: Server info file: ServerInfo { protocol: "uds", language: "java", minimum_numaflow_version: "1.3.1-z", version: "0.8.0", metadata: Some({}) }
2024-11-06T22:57:39.350481Z  INFO numaflow_core::shared::server_info: Version_info: VersionInfo { version: "latest+unknown", build_date: "1970-01-01T00:00:00Z", git_commit: "", git_tag: "", git_tree_state: "", go_version: "unknown", compiler: "", platform: "linux/aarch64" }
2024-11-06T22:57:39.526910Z  INFO numaflow_core::shared::server_info: Server info file: ServerInfo { protocol: "uds", language: "java", minimum_numaflow_version: "1.3.1-z", version: "0.8.0", metadata: Some({}) }
2024-11-06T22:57:39.526929Z  INFO numaflow_core::shared::server_info: Version_info: VersionInfo { version: "latest+unknown", build_date: "1970-01-01T00:00:00Z", git_commit: "", git_tag: "", git_tree_state: "", go_version: "unknown", compiler: "", platform: "linux/aarch64" }
2024-11-06T22:57:39.769657Z  INFO numaflow_core::monovertex::forwarder: Forwarder has started
2024-11-06T22:57:39.801593Z  INFO numaflow_core::metrics: Stopped the Lag-Reader Expose and Builder tasks
2024-11-06T22:57:39.801630Z ERROR numaflow_core: Application error running monovertex: Forwarder("Failed to read messages from source Grpc(\"status: Internal, message: \\\"This is a test exception\\\", details: [], metadata: MetadataMap { headers: {} }\")")
2024-11-06T22:57:39.801633Z  INFO numaflow_core: Gracefully Exiting...
```

**Comment by kohlisid** [comment]
Python 

Source
```

2024-11-06T23:11:49.920674Z  INFO numaflow_core::shared::server_info: Server info file: ServerInfo { protocol: "uds", language: "python", minimum_numaflow_version: "1.3.0-z", version: "0.8.0", metadata: Some({}) }
2024-11-06T23:11:49.920694Z  INFO numaflow_core::shared::server_info: Version_info: VersionInfo { version: "latest+unknown", build_date: "1970-01-01T00:00:00Z", git_commit: "", git_tag: "", git_tree_state: "", go_version: "unknown", compiler: "", platform: "linux/aarch64" }
2024-11-06T23:11:50.924125Z  INFO numaflow_core::shared::utils: Waiting for source client to be ready...
2024-11-06T23:11:50.925425Z  INFO numaflow_core::shared::server_info: Server info file: ServerInfo { protocol: "uds", language: "rust", minimum_numaflow_version: "1.3.1-z", version: "0.1.1", metadata: Some({}) }
2024-11-06T23:11:50.925458Z  INFO numaflow_core::shared::server_info: Version_info: VersionInfo { version: "latest+unknown", build_date: "1970-01-01T00:00:00Z", git_commit: "", git_tag: "", git_tree_state: "", go_version: "unknown", compiler: "", platform: "linux/aarch64" }
2024-11-06T23:11:50.927248Z  INFO numaflow_core::shared::server_info: Server info file: ServerInfo { protocol: "uds", language: "rust", minimum_numaflow_version: "1.3.1-z", version: "0.1.1", metadata: Some({}) }
2024-11-06T23:11:50.927260Z  INFO numaflow_core::shared::server_info: Version_info: VersionInfo { version: "latest+unknown", build_date: "1970-01-01T00:00:00Z", git_commit: "", git_tag: "", git_tree_state: "", go_version: "unknown", compiler: "", platform: "linux/aarch64" }
2024-11-06T23:11:50.933330Z  INFO numaflow_core::monovertex::forwarder: Forwarder has started
2024-11-06T23:11:51.034819Z  INFO numaflow_core::metrics: Stopped the Lag-Reader Expose and Builder tasks
2024-11-06T23:11:51.034860Z ERROR numaflow_core: Application error running monovertex: Forwarder("Failed to read messages from source Grpc(\"status: Unknown, message: \\\"Exception('ERROR IN READ')\\\", details: [], metadata: MetadataMap { headers: {} }\")")
2024-11-06T23:11:51.034863Z  INFO numaflow_core: Gracefully Exiting...


skohli@macos-JQWR9T560R numaflow % kubectl logs simple-mono-vertex-mv-0-dfp5r -f udsource
+ python example.py
2024-11-06 23:11:22 CRITICAL User-Defined Source ReadFn error
Traceback (most recent call last):
  File "/opt/pysetup/examples/source/simple_source/.venv/lib/python3.10/site-packages/pynumaflow/sourcer/servicer/async_servicer.py", line 127, in __invoke_read
    await self.__source_read_handler(
  File "/opt/pysetup/examples/source/simple_source/example.py", line 53, in read_handler
    raise Exception("ERROR IN READ")
Exception: ERROR IN READ
2024-11-06 23:11:22 CRITICAL Traceback (most recent call last):
  File "/opt/pysetup/examples/source/simple_source/.venv/lib/python3.10/site-packages/pynumaflow/sourcer/servicer/async_servicer.py", line 127, in __invoke_read
    await self.__source_read_handler(
  File "/opt/pysetup/examples/source/simple_source/example.py", line 53, in read_handler
    raise Exception("ERROR IN READ")
Exception: ERROR IN READ
2024-11-06 23:11:22 CRITICAL ERROR IN READ
```
