### ISSUE TITLE
PnF crashing due to nil pointer exception

### ISSUE THREAD

**Issue by yhl25** [numaproj/numaflow#491]
```
{"level":"info","ts":1674094418.6177695,"logger":"numaflow.ReduceUDF-processor","caller":"readloop/ordered.go:126","msg":"ReduceOp exiting","vertex":"apigw-metrics-sliding-aggregation","partitionID":"1674074460000-1674074580000-Intuit.sbe.salsa.platform:Intuit.smallbusiness.payrollapi.payrollapi:","error":"context canceled"}
{"level":"info","ts":1674094418.6185737,"logger":"numaflow.ReduceUDF-processor","caller":"readloop/ordered.go:126","msg":"ReduceOp exiting","vertex":"apigw-metrics-sliding-aggregation","partitionID":"1674074460000-1674074580000-Intuit.relationshipscollaboration.checklistservice:NoAuth:","error":"context canceled"}
{"level":"info","ts":1674094418.619379,"logger":"numaflow.ReduceUDF-processor","caller":"readloop/ordered.go:126","msg":"ReduceOp exiting","vertex":"apigw-metrics-sliding-aggregation","partitionID":"1674074460000-1674074580000-Intuit.qbcommerce.channelmgmt:Intuit.identity.authz.authzdecisionservice:","error":"context canceled"}
{"level":"info","ts":1674094418.6376965,"logger":"numaflow.ReduceUDF-processor","caller":"readloop/ordered.go:126","msg":"ReduceOp exiting","vertex":"apigw-metrics-sliding-aggregation","partitionID":"1674074460000-1674074580000-Intuit.platform.wallettestcto.wallettesting:Intuit.cto.iam.ius:","error":"context canceled"}
{"level":"info","ts":1674094418.6385689,"logger":"numaflow.ReduceUDF-processor","caller":"readloop/ordered.go:126","msg":"ReduceOp exiting","vertex":"apigw-metrics-sliding-aggregation","partitionID":"1674074460000-1674074580000-NoAuth:Intuit.app.shell.shellservice:","error":"context canceled"}
{"level":"info","ts":1674094418.6394002,"logger":"numaflow.ReduceUDF-processor","caller":"readloop/ordered.go:126","msg":"ReduceOp exiting","vertex":"apigw-metrics-sliding-aggregation","partitionID":"1674074460000-1674074580000-Intuit.platform.servicesplatform.config:Intuit.qb.ecosytem.company.service:","error":"context canceled"}
{"level":"info","ts":1674094418.6443722,"logger":"numaflow.ReduceUDF-processor","caller":"readloop/ordered.go:126","msg":"ReduceOp exiting","vertex":"apigw-metrics-sliding-aggregation","partitionID":"1674074460000-1674074580000-Intuit.platform.servicesplatform.config:Intuit.money.t360cdmservice:","error":"context canceled"}
{"level":"info","ts":1674094418.6452096,"logger":"numaflow.ReduceUDF-processor","caller":"readloop/ordered.go:126","msg":"ReduceOp exiting","vertex":"apigw-metrics-sliding-aggregation","partitionID":"1674074460000-1674074580000-Intuit.platform.servicesplatform.config:Intuit.identity.authz.authzdecisionservice:","error":"context canceled"}
{"level":"info","ts":1674094418.6460238,"logger":"numaflow.ReduceUDF-processor","caller":"readloop/ordered.go:126","msg":"ReduceOp exiting","vertex":"apigw-metrics-sliding-aggregation","partitionID":"1674074460000-1674074580000-Intuit.platform.servicesplatform.config:Intuit.dev.deployment.securebrowsingservice:","error":"context canceled"}
{"level":"info","ts":1674094418.6468737,"logger":"numaflow.ReduceUDF-processor","caller":"readloop/ordered.go:126","msg":"ReduceOp exiting","vertex":"apigw-metrics-sliding-aggregation","partitionID":"1674074460000-1674074580000-Intuit.platform.servicesplatform.config:Intuit.billingcomm.custpayments.ngpsimulator:","error":"context canceled"}
{"level":"info","ts":1674094418.6477664,"logger":"numaflow.ReduceUDF-processor","caller":"readloop/ordered.go:126","msg":"ReduceOp exiting","vertex":"apigw-metrics-sliding-aggregation","partitionID":"1674074460000-1674074580000-Intuit.platform.ondemandexpertise.understandmeservice:Intuit.platform.servicesplatform.config:","error":"context canceled"}
{"level":"info","ts":1674094418.6619773,"logger":"numaflow.ReduceUDF-processor","caller":"readloop/ordered.go:126","msg":"ReduceOp exiting","vertex":"apigw-metrics-sliding-aggregation","partitionID":"1674074460000-1674074580000-Intuit.platform.gopayment.gps:Intuit.cto.iam.ius:","error":"context canceled"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1a9ae8e]

goroutine 47741 [running]:
github.com/numaproj/numaflow/pkg/reduce/pnf.(*ProcessAndForward).Process(0xc009f7da00, {0x2427270, 0xc000123d80})
	/Users/yhl01/Documents/numaproj/numaflow/pkg/reduce/pnf/processandforward.go:100 +0x26e
github.com/numaproj/numaflow/pkg/reduce/readloop.(*orderedForwarder).reduceOp(0xc0003a6ba0, {0x2427270, 0xc000123d80}, 0xc0118e41c0)
	/Users/yhl01/Documents/numaproj/numaflow/pkg/reduce/readloop/ordered.go:117 +0x1a6
created by github.com/numaproj/numaflow/pkg/reduce/readloop.(*orderedForwarder).schedulePnF
	/Users/yhl01/Documents/numaproj/numaflow/pkg/reduce/readloop/ordered.go:106 +0x3a5
```

**Comment by whynowy** [comment]
Don't see it anymore, might have been fixed by other PRs. Closing it for now.
